name: IPTV Auto Validate

on:
  schedule:
    - cron: '0 */6 * * *'  # 每 6 小时运行
  workflow_dispatch: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Validator
      run: python validate_full.py

    - name: Commit valid results
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add dist/*.m3u || true
        git commit -m "update: valid IPTV channels [skip ci]" || echo "no changes"
        git push || true
