name: IPTV Validator

on:
  schedule:
    - cron: '0 */6 * * *'  # 每 6 小时运行
  workflow_dispatch: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run: pip install -r requirements.txt

    - name: Run Validation
      run: python validate_full.py

    - name: Commit dist files
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add dist/*.m3u
        git commit -m "chore: update dist/*.m3u [skip ci]" || echo "no changes"
        git push
